version: "3.4"

services:
    lachesis:
        image: lachesis:latest
        ports:
            - "18545:18545"
            - "18546:18546"
            - "5050:5050"
        expose:
            - "5050"
        command:
            [
                "--fakenet",
                "1/1",
                "-port=5050",
                "--rpc",
                "--rpcaddr",
                "0.0.0.0",
                "--rpcvhosts",
                "*",
                '--rpccorsdomain="*"',
                '--rpcapi="eth,debug,admin,web3,personal,net,txpool,ftm,sfc"',
                "--ws",
                "--wsaddr",
                "0.0.0.0",
                '--wsorigins="*"',
                '--wsapi="eth,debug,admin,web3,personal,net,txpool,ftm,sfc"',
                "--nocheckversion",
                "--nousb",
            ]
        restart: "no"
        networks:
            - oracle_network
    generate_deps:
        build:
            context: ../
            dockerfile: integration_tests/Dockerfile.deps
        volumes:
            - ./accounts-configs:/usr/src/app/accounts-configs
        restart: "no"
        depends_on:
            - lachesis
        networks:
            - oracle_network
    # test_source:
    #     build:
    #         context: ../
    #         dockerfile: testDataSource/Dockerfile
    #     restart: always
    #     networks:
    #         - oracle_network
    # oracle-backend-app-1:
    #     build:
    #         context: ../
    #         dockerfile: oracleApp/Dockerfile
    #         args:
    #             CONFIG: integration_tests/accounts-configs/account-config1/config.js
    #     restart: always
    #     depends_on:
    #         - lachesis
    #         - test_source
    #         - generate_deps
    #     networks:
    #         - oracle_network
    # oracle-backend-app-2:
    #     build:
    #         context: ../
    #         dockerfile: oracleApp/Dockerfile
    #         args:
    #             CONFIG: integration_tests/accounts-configs/account-config2/config.js
    #     restart: always
    #     depends_on:
    #         - lachesis
    #         - test_source
    #         - generate_deps
    #     networks:
    #         - oracle_network
    # oracle-backend-app-3:
    #     build:
    #         context: ../
    #         dockerfile: oracleApp/Dockerfile
    #         args:
    #             CONFIG: integration_tests/accounts-configs/account-config3/config.js
    #     restart: always
    #     depends_on:
    #         - lachesis
    #         - test_source
    #         - generate_deps
    #     networks:
    #         - oracle_network

networks:
    oracle_network:
